using IMS.Domain.Common;
using IMS.Domain.Entities.MasterData;
using IMS.Domain.Exceptions;

namespace IMS.Domain.Entities.Inventory;

/// <summary>
/// Doc §5.1 - the current quantity of an item at a specific location, in a specific
/// status, for a specific lot / serial / license plate.
///
/// Uniqueness (doc §5.1): WarehouseId + LocationId + ItemId + InventoryStatusId +
/// LotId + SerialId + LicensePlateId. PostgreSQL treats NULLs as distinct in unique
/// indexes, which the doc explicitly flags; the migration therefore builds the index
/// over COALESCE(...) sentinels so a null lot/serial/LPN still collides correctly.
///
/// AvailableQuantity is a STORED GENERATED column computed by PostgreSQL as
/// OnHand - Allocated - Hold, so the §5.1 formula can never drift from the stored data.
/// </summary>
public class InventoryBalance : BaseEntity, IWarehouseScoped
{
    public Guid WarehouseId { get; set; }
    public Warehouse Warehouse { get; set; } = null!;

    public Guid LocationId { get; set; }
    public Location Location { get; set; } = null!;

    public Guid ItemId { get; set; }
    public ItemMaster Item { get; set; } = null!;

    public Guid InventoryStatusId { get; set; }
    public InventoryStatus InventoryStatus { get; set; } = null!;

    public Guid? LotId { get; set; }
    public Lot? Lot { get; set; }

    public Guid? SerialId { get; set; }
    public SerialNumber? Serial { get; set; }

    public Guid? LicensePlateId { get; set; }
    public LicensePlate? LicensePlate { get; set; }

    /// <summary>Physical quantity present. Changed by receipt, movement, pick, ship and adjustment.</summary>
    public decimal OnHandQuantity { get; set; }

    /// <summary>Reserved for orders. Doc §7.3 - allocation moves this, never OnHand.</summary>
    public decimal AllocatedQuantity { get; set; }

    /// <summary>Blocked from allocation without changing status, e.g. pending inspection.</summary>
    public decimal HoldQuantity { get; set; }

    /// <summary>
    /// Read-only projection of the database-generated column
    /// (OnHandQuantity - AllocatedQuantity - HoldQuantity).
    /// </summary>
    public decimal AvailableQuantity { get; private set; }

    // --- Doc §10 "Inventory uzerinde": data required by future FIFO/FEFO algorithms. ---

    /// <summary>When this stock first entered the warehouse. Backs future FIFO.</summary>
    public DateTimeOffset ReceivedAt { get; set; }

    /// <summary>When this balance was last touched. Backs slow-mover analysis.</summary>
    public DateTimeOffset? LastMovementAt { get; set; }

    /// <summary>
    /// Doc §5.1 and §11.11 - optimistic concurrency token. Incremented on every save;
    /// a stale value aborts the transaction.
    /// </summary>
    public int Version { get; set; }

    /// <summary>
    /// In-memory recomputation of the §5.1 formula. The persisted AvailableQuantity is
    /// generated by PostgreSQL; this mirrors it for domain logic and unit tests that
    /// never touch the database.
    /// </summary>
    public decimal ComputeAvailable() => OnHandQuantity - AllocatedQuantity - HoldQuantity;

    /// <summary>
    /// Increases allocated quantity after verifying availability.
    /// Doc §11.1 (no allocation without available stock) and §11.2 (on-hand unchanged).
    /// </summary>
    public void Allocate(decimal quantity, string sku)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Allocation quantity must be greater than zero.");

        if (ComputeAvailable() < quantity)
            throw new InsufficientStockException(
                new StockShortfall(ItemId, sku, quantity, ComputeAvailable()));

        AllocatedQuantity += quantity;
    }

    /// <summary>Releases a previous allocation without touching on-hand.</summary>
    public void Deallocate(decimal quantity)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Deallocation quantity must be greater than zero.");

        if (AllocatedQuantity < quantity)
            throw new BusinessRuleViolationException(
                $"Cannot deallocate {quantity}; only {AllocatedQuantity} is allocated on this balance.");

        AllocatedQuantity -= quantity;
    }

    /// <summary>
    /// Removes stock physically. Doc §11.3 - shipment reduces on-hand AND allocated.
    /// Guards against negative stock (acceptance scenario 3).
    /// </summary>
    public void ShipAllocated(decimal quantity, string sku)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Ship quantity must be greater than zero.");

        if (AllocatedQuantity < quantity)
            throw new BusinessRuleViolationException(
                $"Cannot ship {quantity}; only {AllocatedQuantity} is allocated on this balance.");

        if (OnHandQuantity < quantity)
            throw new InsufficientStockException(
                new StockShortfall(ItemId, sku, quantity, OnHandQuantity));

        OnHandQuantity -= quantity;
        AllocatedQuantity -= quantity;
    }

    /// <summary>Adds physical stock (receipt, positive adjustment, inbound movement leg).</summary>
    public void AddStock(decimal quantity)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Quantity to add must be greater than zero.");

        OnHandQuantity += quantity;
    }

    /// <summary>
    /// Removes physical stock that is not reserved (movement source leg, negative
    /// adjustment). Never allows the balance to go negative, and never consumes
    /// quantity that is allocated or on hold.
    /// </summary>
    public void RemoveStock(decimal quantity, string sku)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Quantity to remove must be greater than zero.");

        if (ComputeAvailable() < quantity)
            throw new InsufficientStockException(
                new StockShortfall(ItemId, sku, quantity, ComputeAvailable()));

        OnHandQuantity -= quantity;
    }

    /// <summary>Moves quantity from free stock into hold, blocking it from allocation.</summary>
    public void PlaceHold(decimal quantity, string sku)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Hold quantity must be greater than zero.");

        if (ComputeAvailable() < quantity)
            throw new InsufficientStockException(
                new StockShortfall(ItemId, sku, quantity, ComputeAvailable()));

        HoldQuantity += quantity;
    }

    /// <summary>Releases held quantity back to available.</summary>
    public void ReleaseHold(decimal quantity)
    {
        if (quantity <= 0)
            throw new BusinessRuleViolationException("Release quantity must be greater than zero.");

        if (HoldQuantity < quantity)
            throw new BusinessRuleViolationException(
                $"Cannot release {quantity}; only {HoldQuantity} is on hold.");

        HoldQuantity -= quantity;
    }

    /// <summary>True when the row carries no quantity at all and can be pruned.</summary>
    public bool IsEmpty() => OnHandQuantity == 0m && AllocatedQuantity == 0m && HoldQuantity == 0m;
}
